### ISSUE TITLE
"Click to reveal" for Search

### ISSUE THREAD

**Issue by herohousecreative** [rkrussel/nbba-website#5]
We need to develop HTML/CSS/JS to accommodate a collapsed Search box.

Think: A magnifying glass icon that expands to a search field on click, and closes on submission.

Thoughts?

**Comment by rkrussel** [comment]
I could certainly create something like that... but doesn't wordpress have
plugins for such things?

Rich

On Wed, Feb 21, 2018 at 6:26 AM, herohousecreative <notifications@github.com

**Comment by herohousecreative** [comment]
It’s possible something exists – but not likely as an addition to a template file (front-page.php.) I have a few solutions I’m going to try and we’ll see what we get.

Thanks!
Justin

**Comment by rkrussel** [comment]
Where is the file that has the current search bar/other header stuff?

**Comment by herohousecreative** [comment]
You should find that in /lib/theme-defaults.php.


Sent from my iPhone (and most likely transcribed by Siri)

On Feb 21, 2018, at 11:16 PM, rkrussel <notifications@github.com<mailto:notifications@github.com>> wrote:


Where is the file that has the current search bar/other header stuff?

**Comment by rkrussel** [comment]
I pushed a couple of minor commits but I was on my master branch. Not sure
if you'll be able to pull those but lemme know I'll try to fix it

**Comment by herohousecreative** [comment]
Resolved.b
